version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/
      - DIFY_API_KEY=${DIFY_API_KEY}
      - DIFY_API_URL=${DIFY_API_URL}
      - WECHAT_TOKEN=${WECHAT_TOKEN}
      - WECHAT_ENCODING_AES_KEY=${WECHAT_ENCODING_AES_KEY}
      - WECHAT_CORP_ID=${WECHAT_CORP_ID}
    depends_on:
      - rabbitmq
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

  # 前端服务
  frontend:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    networks:
      - app-network

  # RabbitMQ服务
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"   # AMQP协议端口
      - "15672:15672" # 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - app-network

  # 个微服务
  gewechat:
    image: registry.cn-chengdu.aliyuncs.com/tu1h/wechotd:alpine
    restart: always
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${GEWECHAT_API_KEY}
      - CALLBACK_URL=${DIFY_API_URL}/wechat/callback
    volumes:
      - ./src/wechat/config:/app/config
      - ./gewechat/data/log:/root/temp/log
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq-data:
